### ISSUE TITLE
Discord authentication issue

### ISSUE THREAD

**Issue by hsutaiyu** [torusresearch/torus-direct-web-sdk#28]
Can't login using the same token within 30 minutes

**Comment by chaitanyapotti** [comment]
This is an issue with discord because they don't re-create an access token until the old one expires.
We need a new token for every new login. 
The only way to invalidate a token is to send a post request to discord server along with client secret.

Direct Auth is a frontend library and hence, we don't require client secret and can't invalidate the token. 
So, you need to create a backend server and do the invalidation yourself.

Here's some Node.js code to invalidate the discord token
```js
 const { token } = req.body;
    const formData = new FormData();
    formData.append("token", token);
    await axios.post("https://discordapp.com/api/oauth2/token/revoke", formData, {
      headers: {
        ...formData.getHeaders(),
        Authorization: `Basic ${Buffer.from(`${DISCORD_CLIENT_ID}:${DISCORD_CLIENT_SECRET}`, "binary").toString("base64")}`,
      },
    });
```

Currently, the direct auth library doesn't return the access token to the end user. We are planning to enable this in the next release so that you can do the invalidation.

Let me know if this solves the issue
